# A sample Gemfile
source "http://rubygems.org"

gem "rack"
gem "sinatra"
gem "mustache"
gem "rack-auth-dscildap", :path => "/Users/thom/code/central-rack-auth-ldap"
gem "amiba", :path =>"/Users/thom/code/amiba"

group :development do
  gem "shotgun"
end
