source "http://rubygems.org"

gem "thor", "~>0.14.6", require: %w{thor thor/group thor/runner}
gem "tilt", "~>1.1"
gem "haml", "~>3.0.25"
gem "activesupport", "~>3.0.3", require: 'active_support/all'
gem "activemodel", "~>3.0.3", require: 'active_model'
gem "i18n"
gem "rdiscount"

gem "amiba"
